export const unknownEntityLogo = "logos/unknown.png";

/**
 * Lookup of entity id to their logo
 * The entity id is based on that returned by the Rated.Network API for leader-board population
 */
export const entityLogos: Record<string, string> = {
  Abyss: "logos/abyss.png",
  Ankr: "logos/ankr.png",
  "augur.eth": "logos/augur.eth.png",
  Binance: "logos/binance.png",
  "Bitcoin Suisse": "logos/bitcoin_suisse.png",
  Bitfinex: "logos/bitfinex.png",
  Bitstamp: "logos/bitstamp.png",
  Bloxstaking: "logos/bloxstaking.png",
  "Celsius Network": "logos/celsius_network.png",
  Coinbase: "logos/coinbase.png",
  "Cream Finance": "logos/cream_finance.png",
  "Ether Capital": "logos/ether_capital.jpeg",
  "Ether Capital via Figment": "logos/figment.png",
  Huobi: "logos/huobi.png",
  Kraken: "logos/kraken.png",
  Kucoin: "logos/kucoin.png",
  "Ledger Live": "logos/ledger.png",
  Lido: "logos/lido.png",
  "Lighthouse Client Team": "logos/lighthouse_client_team.png",
  "Nimbus Client Team": unknownEntityLogo,
  OKex: "logos/okex.png",
  "Prysm Client Team": unknownEntityLogo,
  Rocketpool: "logos/rocketpool.png",
  StakeHound: "logos/stakehound.png",
  StakeWise: "logos/stakewise.png",
  "StakeWise Solos": "logos/stakewise_solos.png",
  "Staked.us": "logos/staked.us.png",
  Stakefish: "logos/stakefish.png",
  "Teku Client Team": unknownEntityLogo,
  "Vitalik Buterin": unknownEntityLogo,
  Wexexchange: "logos/wexexchange.png",
  "ads.eth": unknownEntityLogo,
  "permafrost.eth": unknownEntityLogo,
  "sushichef.eth": unknownEntityLogo,
  "therealyoshi.eth": unknownEntityLogo,
  "wedex.eth": "logos/wedex.eth.png",
  "williamgrimes.eth": unknownEntityLogo,
};
