name: Build Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - 'apps/blockIndexer/**/*'
      - 'packages/**/*'
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GKE_CLUSTER: cluster-1    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: block-indexer # Add your deployment name here.
  DOCKERFILE: apps/blockIndexer/Dockerfile
  IMAGE_TAG: mev-watch/block-indexer:${{ github.sha }}
  LATEST_IMAGE_TAG: mev-watch/block-indexer:latest

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - name: GCloud CLI Setup
      uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - name: GCP Auth
      run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Build the Docker image
    - name: Build
      run: |-
        docker pull $LATEST_IMAGE_TAG || true
        yarn docker:build:server:ci

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$IMAGE_TAG"
        docker push "gcr.io/$LATEST_IMAGE_TAG"
